media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: "_posts"
    view:
      fields: [title, date]
    fields:
      - { name: date, label: Date, type: date }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  - name: config
    label: Jekyll config
    path: "_config.yml"
    type: file