media: media
content:
  - path: "_posts"
    type: collection
    name: posts
    label: Posts
    view:
      fields: [title]
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  - path: "_config.yml"
    type: file
    name: config
    label: Jekyll config